/* ===================================================================
   PRIYA STUDIO - PRODUCT DATABASE
   Curated catalog for Resin Art, Jewellery & Custom T-Shirts
   =================================================================== */

const PRODUCTS_DATA = [
  // --- RESIN ART ---
  {
    id: 'varmala-preservation-frame-01',
    slug: 'custom-varmala-preservation-frame-personalized-wedding-memory',
    name: 'Custom Varmala Preservation Frame – Personalized Wedding Memory',
    category: 'resin-art',
    subCategory: 'varmala-preservation',
    categoryName: 'Resin Art',
    collection: 'Varmala Preservation',
    price: 4000,
    productType: 'Varmala Preservation Frame',
    material: 'Resin & Decorative Elements',
    customization: 'Names + Photograph + Design',
    style: 'Personalized & Handcrafted',
    idealFor: 'Wedding & Anniversary Memories',
    madeFor: 'Bride & Groom',
    rating: 5.0,
    reviewsCount: 58,
    badge: 'Wedding Memory',
    badgeType: 'resin',
    badges: ['Wedding Memory', 'Handcrafted Resin', 'Personalized', 'Bestseller'],
    image: 'images/custom-varmala-preservation-frame-1.jpg',
    images: [
      'images/custom-varmala-preservation-frame-1.jpg',
      'images/custom-varmala-preservation-frame-2.jpg'
    ],
    shortDescription: 'Turn your special wedding memories into a timeless keepsake with a beautifully handcrafted personalized Varmala Preservation Frame.',
    description: 'Your wedding day is a memory you’ll cherish forever — now preserve one of its most beautiful moments in a stunning piece of art. ✨\n\nOur Custom Varmala Preservation Frame transforms your precious wedding memories into an elegant handcrafted keepsake. Designed with beautiful resin detailing, decorative elements, personalized names and your favorite wedding photograph, every frame is created to tell your unique love story.\n\nThe frame can beautifully incorporate elements such as Varmala details, flowers, photographs, pearls, decorative embellishments and personalized names, creating a meaningful piece that you can proudly display in your home.',
    keyFeatures: [
      'Fully personalized wedding keepsake',
      'Custom couple photograph',
      'Couple names can be added',
      'Beautiful handcrafted resin artwork',
      'Elegant decorative embellishments',
      'Unique design created for your wedding memories',
      'Premium display-worthy finish',
      'Each piece is individually handcrafted'
    ],
    perfectFor: [
      'Varmala Preservation',
      'Wedding Memory Preservation',
      'Anniversary Gift',
      'Wedding Gift',
      'Couple Keepsake',
      'Bride & Groom Memory',
      'Wedding Home Décor',
      'Special Anniversary Surprise'
    ],
    howItWorks: [
      '1. Place Your Order: Choose your preferred preservation design.',
      '2. Share Your Memories: Send us your wedding photograph and required personalization details.',
      '3. We Create Your Keepsake: Our artisans carefully create your customized preservation artwork.',
      '4. Receive Your Memory ❤️: Your personalized Varmala Preservation is safely prepared and delivered to you.'
    ],
    whyChoose: 'Because some memories deserve more than a photograph. Preserve the emotions, celebrations and love of your wedding day in a beautiful handcrafted artwork that you can treasure for years to come.',
    websiteCTA: 'Preserve Your Wedding Story Forever ❤️ | Create Your Custom Varmala Frame →',
    options: ['Customized Frame (With Photo & Names)'],
    featured: true,
    inStock: true
  },
  {
    id: 'resin-earring-01',
    slug: 'orange-stone-oxidised-silver-jhumka-earrings',
    name: 'Orange Stone Oxidised Silver Jhumka Earrings for Women',
    category: 'resin-art',
    subCategory: 'resin-earrings',
    categoryName: 'Resin Art',
    collection: 'Resin Earrings',
    price: 400,
    productType: 'Statement Earrings / Jhumka-Style Earrings',
    design: 'Traditional Round',
    color: 'Orange',
    metalFinish: 'Oxidised Silver-Tone',
    stone: 'Orange Stone Detailing',
    style: 'Traditional & Festive',
    occasion: 'Festive, Ethnic & Party Wear',
    idealFor: 'Women & Girls',
    gender: 'Women & Girls',
    rating: 5.0,
    reviewsCount: 46,
    badge: 'Navratri Special',
    badgeType: 'sale',
    badges: ['Navratri Special', 'Festive Favourite', 'Statement Jewellery', 'Trending'],
    image: 'images/orange-stone-oxidised-silver-jhumka-1.jpg',
    images: [
      'images/orange-stone-oxidised-silver-jhumka-1.jpg',
      'images/orange-stone-oxidised-silver-jhumka-2.jpg'
    ],
    websiteHighlight: 'Bring traditional charm to your festive look with a vibrant pop of orange. 🧡',
    shortDescription: 'A stunning pair of traditional oxidised silver earrings featuring vibrant orange stone detailing and delicate silver bead accents — perfect for festive and ethnic looks.',
    description: 'Add a beautiful traditional touch to your jewellery collection with these Orange Stone Oxidised Silver Earrings. Featuring a bold round design, vibrant orange stone detailing and intricate oxidised-style silver work, these earrings create a gorgeous statement look.\n\nThe detailed silver-tone border and layered hanging beads add beautiful movement and traditional charm. Pair them with kurtis, sarees, lehengas, Anarkali suits or other ethnic outfits for festivals, Navratri, weddings and special occasions.\n\nThe vibrant orange centre makes these earrings especially eye-catching and perfect for adding a pop of colour to your festive wardrobe. 🧡✨',
    keyFeatures: [
      'Vibrant orange stone centre',
      'Traditional oxidised silver-tone design',
      'Intricate round detailing',
      'Decorative hanging silver-tone beads',
      'Statement-style earrings',
      'Perfect for ethnic and festive outfits',
      'Eye-catching traditional appearance',
      'Great gifting option'
    ],
    perfectFor: [
      'Navratri & Garba',
      'Diwali & festive celebrations',
      'Weddings & functions',
      'Sarees & lehengas',
      'Kurtis & Anarkali outfits',
      'Traditional photoshoots',
      'Parties & cultural events',
      'Festive gifting'
    ],
    options: ['Standard Pair'],
    featured: true,
    inStock: true
  },

  // --- JEWELLERY ---
  {
    id: 'anti-03',
    slug: 'elegant-leaf-design-stud-earrings',
    name: 'Elegant Leaf Design Stud Earrings with Crystal Detail – Gold Colour',
    category: 'jewellery',
    subCategory: 'anti-tarnish',
    categoryName: 'Anti Tarnish',
    price: 299,
    productType: 'Stud Earrings',
    design: 'Leaf / Fan Inspired',
    color: 'Gold Colour',
    accent: 'Crystal-Style Stone',
    style: 'Elegant & Feminine',
    occasion: 'Casual, Festive & Party Wear',
    idealFor: 'Women & Girls',
    gender: 'Women & Girls',
    rating: 4.9,
    reviewsCount: 42,
    badge: 'Anti-Tarnish',
    badgeType: 'jewel',
    image: 'images/elegant-leaf-design-stud-earrings.jpg',
    shortDescription: 'Beautiful leaf-inspired stud earrings featuring delicate textured detailing and a sparkling centre accent for an elegant everyday look.',
    description: 'Add a graceful touch to your style with these Leaf Design Stud Earrings. Inspired by elegant flowing leaves, the earrings feature fine textured detailing combined with a beautiful round crystal-style centre accent.\n\nTheir sophisticated design works beautifully with both Indian ethnic wear and modern Western outfits, making them a versatile addition to your jewellery collection.',
    keyFeatures: [
      'Elegant leaf-inspired design',
      'Gold-colour finish',
      'Fine textured detailing',
      'Crystal-style centre accent',
      'Stylish and sophisticated appearance',
      'Suitable for everyday and special occasions',
      'Great gifting option'
    ],
    options: ['Gold Colour'],
    featured: true,
    inStock: true
  },
  {
    id: 'anti-04',
    slug: 'elegant-multi-layer-hoop-earrings',
    name: 'Elegant Multi-Layer Hoop Earrings for Women – Gold Colour',
    category: 'jewellery',
    subCategory: 'anti-tarnish',
    categoryName: 'Anti Tarnish',
    price: 249,
    productType: 'Hoop Earrings',
    design: 'Multi-Layer',
    color: 'Gold Colour',
    style: 'Modern & Elegant',
    occasion: 'Daily, Party & Festive Wear',
    idealFor: 'Women & Girls',
    gender: 'Women & Girls',
    rating: 4.9,
    reviewsCount: 38,
    badge: 'Anti-Tarnish',
    badgeType: 'jewel',
    image: 'images/elegant-multi-layer-hoop-earrings.jpg',
    shortDescription: 'Stylish multi-layer hoop earrings with a sleek polished finish, perfect for adding a fashionable touch to everyday and occasion looks.',
    description: 'Upgrade your jewellery collection with these Elegant Multi-Layer Hoop Earrings. Featuring multiple smooth curved bands arranged in a stylish layered design, these earrings create a bold yet sophisticated look.\n\nThe versatile design makes them easy to pair with casual outfits, office wear, ethnic dresses and party looks. A perfect accessory when you want a simple outfit to look more stylish.',
    keyFeatures: [
      'Stylish multi-layer design',
      'Beautiful gold-colour finish',
      'Modern and elegant look',
      'Easy to style with different outfits',
      'Suitable for casual and occasion wear',
      'Fashion jewellery for women',
      'Ideal for gifting'
    ],
    options: ['Gold Colour'],
    featured: true,
    inStock: true
  },
  {
    id: 'anti-05',
    slug: 'stylish-woven-pattern-stud-earrings',
    name: 'Stylish Woven Pattern Stud Earrings for Women – Gold Colour',
    category: 'jewellery',
    subCategory: 'anti-tarnish',
    categoryName: 'Anti Tarnish',
    price: 149,
    productType: 'Stud Earrings',
    design: 'Woven / Interwoven Pattern',
    color: 'Gold Colour',
    style: 'Modern & Statement',
    occasion: 'Daily, Party & Festive Wear',
    idealFor: 'Women & Girls',
    gender: 'Women & Girls',
    rating: 4.9,
    reviewsCount: 29,
    badge: 'Anti-Tarnish',
    badgeType: 'jewel',
    image: 'images/stylish-woven-pattern-stud-earrings.jpg',
    shortDescription: 'A bold and contemporary pair of stud earrings featuring a unique woven pattern and glossy finish for a statement-making look.',
    description: 'Make your everyday style stand out with these Woven Pattern Stud Earrings. Designed with an eye-catching interwoven pattern and smooth rounded edges, these earrings offer a contemporary and fashionable appearance.\n\nThe statement design can instantly elevate casual, office, festive and party outfits, making them a versatile accessory for your jewellery collection.',
    keyFeatures: [
      'Unique woven pattern design',
      'Gold-colour finish',
      'Bold statement appearance',
      'Smooth polished look',
      'Modern and fashionable style',
      'Versatile for different outfits',
      'Suitable for gifting'
    ],
    options: ['Gold Colour'],
    featured: true,
    inStock: true
  },
  {
    id: 'anti-06',
    slug: 'pearl-shell-charm-bracelet',
    name: 'Pearl & Shell Charm Bracelet – Elegant Gold-Tone Fashion Jewellery',
    category: 'jewellery',
    subCategory: 'anti-tarnish',
    categoryName: 'Anti Tarnish',
    price: 99,
    productType: 'Bracelet',
    design: 'Pearl & Shell Charm',
    color: 'Gold Colour',
    accent: 'Pearl-Style Beads',
    charm: 'Shell-Inspired',
    closure: 'Lobster Clasp',
    style: 'Elegant & Feminine',
    occasion: 'Daily, Party & Festive Wear',
    idealFor: 'Women & Girls',
    gender: 'Women & Girls',
    rating: 5.0,
    reviewsCount: 34,
    badge: 'Hot Deal',
    badgeType: 'sale',
    image: 'images/pearl-shell-charm-bracelet.jpg',
    sellingLine: '“Delicate pearls, a beautiful shell, and effortless elegance — all in one bracelet. ✨”',
    shortDescription: 'A delicate gold-tone bracelet featuring dainty pearl accents and a beautiful shell-inspired charm, designed for a feminine and elegant everyday look.',
    description: 'Add a touch of effortless elegance to your jewellery collection with this Pearl & Shell Charm Bracelet. Featuring a delicate chain design decorated with small pearl-style beads and a beautiful shell-inspired pendant, this bracelet creates a graceful and feminine look.\n\nThe combination of the gold-tone chain, soft pearl accents and statement shell charm makes it perfect for styling with both modern and traditional outfits. Wear it alone for a subtle look or pair it with other bracelets for a trendy layered style.',
    keyFeatures: [
      'Elegant pearl-accented design',
      'Beautiful shell-inspired charm',
      'Gold-tone finish',
      'Delicate and feminine appearance',
      'Adjustable extension chain',
      'Lobster-style clasp',
      'Easy to style with different outfits',
      'Suitable for everyday and special occasions',
      'Perfect gifting option'
    ],
    perfectFor: [
      'Everyday wear',
      'Casual & office outfits',
      'Date nights',
      'Parties & dinners',
      'Festive occasions',
      'Beach-inspired looks',
      'Layered bracelet styling',
      'Birthday & special-occasion gifting'
    ],
    options: ['Gold Colour (Adjustable)'],
    featured: true,
    inStock: true
  },
  {
    id: 'anti-07',
    slug: 'elegant-gold-tone-knot-design-kada',
    name: 'Elegant Gold-Tone Knot Design Kada for Women',
    category: 'jewellery',
    subCategory: 'anti-tarnish',
    categoryName: 'Anti Tarnish',
    price: 179,
    productType: 'Kada / Open Cuff Bracelet',
    design: 'Knot & Loop',
    color: 'Gold Colour',
    finish: 'Polished',
    style: 'Modern & Elegant',
    occasion: 'Daily, Festive & Party Wear',
    idealFor: 'Women & Girls',
    gender: 'Women & Girls',
    rating: 5.0,
    reviewsCount: 27,
    badge: 'Popular',
    badgeType: 'jewel',
    image: 'images/elegant-gold-tone-knot-design-kada.jpg',
    sellingLine: '“A little shine, a lot of elegance. ✨”',
    shortDescription: 'A stylish open kada featuring a unique loop-and-knot design with a sleek polished finish — perfect for adding an elegant touch to any outfit.',
    description: 'Elevate your everyday jewellery collection with this Elegant Gold-Tone Knot Design Kada. Designed with a sleek open-cuff silhouette and a beautiful intertwined loop detail at the centre, this kada offers a modern yet timeless look.\n\nIts minimal and sophisticated design makes it easy to pair with Indian ethnic wear, Western outfits, office looks and party dresses. Whether worn alone for a subtle statement or paired with other accessories, this kada adds an effortlessly stylish finish to your look.',
    keyFeatures: [
      'Elegant open-kada design',
      'Unique loop and knot-inspired centre detail',
      'Smooth polished gold-tone finish',
      'Modern and sophisticated appearance',
      'Easy to style with different outfits',
      'Suitable for daily and occasion wear',
      'Great gifting option'
    ],
    perfectFor: [
      'Daily wear',
      'Office & casual looks',
      'Festive occasions',
      'Parties & dinners',
      'Ethnic outfits',
      'Western outfits',
      'Gifting'
    ],
    options: ['Gold Colour (Free Size Open Cuff)'],
    featured: true,
    inStock: true
  },
  {
    id: 'anti-08',
    slug: 'elegant-heart-pendant-chain',
    name: 'Elegant Heart Pendant Chain for Women – Gold-Tone',
    category: 'jewellery',
    subCategory: 'anti-tarnish',
    categoryName: 'Anti Tarnish',
    price: 199,
    productType: 'Pendant Chain / Necklace',
    design: 'Heart Pendant',
    color: 'Gold Colour',
    style: 'Minimal & Elegant',
    occasion: 'Daily, Casual & Party Wear',
    idealFor: 'Women & Girls',
    gender: 'Women & Girls',
    rating: 5.0,
    reviewsCount: 39,
    badge: 'Romantic',
    badgeType: 'jewel',
    image: 'images/elegant-heart-pendant-chain.jpg',
    sellingLine: '“Wear your heart with elegance. ❤️✨”',
    shortDescription: 'A delicate heart pendant chain featuring a beautiful intertwined design, perfect for adding a romantic and elegant touch to your everyday style.',
    description: 'Express your style with this Elegant Heart Pendant Chain, designed with a delicate chain and a beautiful open-heart pendant featuring an intertwined detail at the top.\n\nIts minimal and romantic design makes it perfect for everyday wear, casual outings, office looks, date nights and special occasions. The elegant gold-tone finish adds a subtle touch of sophistication and pairs beautifully with both Western and ethnic outfits.\n\nWhether you\'re treating yourself or looking for a thoughtful gift for someone special, this heart pendant chain is a timeless addition to any jewellery collection. ✨',
    keyFeatures: [
      'Beautiful heart-shaped pendant',
      'Unique intertwined heart design',
      'Delicate and elegant chain',
      'Attractive gold-tone finish',
      'Minimal and versatile style',
      'Easy to pair with different outfits',
      'Suitable for everyday and occasion wear',
      'Perfect gifting option'
    ],
    perfectFor: [
      'Everyday wear',
      'Office & casual outfits',
      'Date nights',
      'Parties & dinners',
      'Festive occasions',
      "Valentine's Day & special moments",
      'Birthday & anniversary gifting'
    ],
    options: ['Gold Colour (Adjustable Chain)'],
    featured: true,
    inStock: true
  },

  // --- T-SHIRTS & APPAREL ---
  {
    id: 'black-vintage-graphic-tshirt',
    slug: 'black-vintage-graphic-tshirt',
    name: 'Black Vintage Graphic T-Shirt',
    category: 't-shirts',
    categoryName: 'T-Shirts',
    collection: 'Vintage T-Shirts',
    price: 350,
    color: 'Black',
    style: 'Vintage / Streetwear',
    gender: 'Unisex',
    rating: 4.9,
    reviewsCount: 38,
    badge: 'Vintage',
    badgeType: 'tshirt',
    image: 'images/black-vintage-graphic-tshirt.jpg',
    shortDescription: 'A classic black T-shirt featuring a clean white VINTAGE chest print. A versatile everyday streetwear essential for casual and modern styling.',
    description: 'Upgrade your everyday wardrobe with this stylish Black Vintage Graphic T-Shirt. The classic black color is paired with a clean white VINTAGE chest print, creating a timeless and minimal streetwear look. Its versatile design makes it easy to style with jeans, cargos, shorts and sneakers. Perfect for casual outings, travel, college, weekends and everyday wear.',
    keyFeatures: [
      'Black color',
      'White VINTAGE chest print',
      'Vintage-inspired design',
      'Casual streetwear aesthetic',
      'Versatile everyday styling',
      'Easy to pair with jeans and cargos',
      'Unisex styling'
    ],
    options: ['S', 'M', 'L', 'XL', 'XXL'],
    seoTitle: 'Black Vintage Graphic T-Shirt ₹350 | Vintage Streetwear',
    seoDescription: 'Shop the Black Vintage Graphic T-Shirt for ₹350, featuring a clean white VINTAGE chest print and versatile everyday streetwear style.',
    featured: true,
    inStock: true
  },
  {
    id: 'black-vintage-headphone-graphic-tshirt',
    slug: 'black-vintage-headphone-graphic-tshirt',
    name: 'Black Vintage Headphone Graphic T-Shirt',
    category: 't-shirts',
    categoryName: 'T-Shirts',
    collection: 'Vintage T-Shirts',
    price: 350,
    color: 'Black',
    style: 'Vintage / Graphic / Streetwear',
    gender: 'Unisex',
    rating: 4.8,
    reviewsCount: 29,
    badge: 'Retro Graphic',
    badgeType: 'tshirt',
    image: 'images/black-vintage-headphone-graphic-tshirt.jpg',
    shortDescription: 'A stylish black T-shirt featuring a bold colorful vintage-inspired headphone and floral graphic on the back.',
    description: 'Make a statement with this Black Vintage Headphone Graphic T-Shirt. The classic black T-shirt features a bold colorful retro-inspired headphone and floral artwork on the back. The detailed graphic creates a distinctive vintage aesthetic while keeping the overall design easy to wear. Pair it with jeans, cargos, shorts or sneakers for a casual streetwear look.',
    keyFeatures: [
      'Black color',
      'Large colorful back graphic',
      'Vintage-inspired headphone artwork',
      'Floral graphic detailing',
      'Retro streetwear aesthetic',
      'Statement casual design',
      'Unisex styling'
    ],
    options: ['S', 'M', 'L', 'XL', 'XXL'],
    seoTitle: 'Black Vintage Headphone Graphic T-Shirt ₹350 | Retro Streetwear',
    seoDescription: 'Shop the Black Vintage Headphone Graphic T-Shirt for ₹350, featuring a colorful retro-inspired headphone and floral back graphic.',
    featured: true,
    inStock: true
  }
];

// WhatsApp Business Contact Configuration
const STUDIO_CONFIG = {
  name: 'Priya Art Studio',
  tagline: "Where Creativity Meets Your Everyday Style — Handcrafted Resin Art, Stylish T-Shirts & Elegant Jewellery.",
  phone: '919876543210', // User can update their real WhatsApp number here
  email: 'contact@priyaartstudio.com',
  address: 'Priya Art Studio, Ahmedabad, Gujarat, India',
  currency: '₹',
  freeShippingThreshold: 999,
  couponCodes: {
    'PRIYA10': 10,  // 10% discount
    'WELCOME15': 15 // 15% discount
  }
};
